name: diskmelts
channels:
  - conda-forge
dependencies:
  - python = 3.12
  - pip >= 24.0
  - setuptools >= 61.0

  # DiskMELTS runtime dependencies
  - numpy
  - pandas >= 2.0
  - scipy
  - scikit-learn >= 1.4
  - pytorch
  - matplotlib >= 3.8

  # For running example notebooks
  - jupyter

  # Install DiskMELTS in editable mode
  - pip:
      - -e .
